image: node:10

stages:
  - build
  - test

build project:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
     - ./build
  
test project:
  stage: test
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"